### ISSUE TITLE
moFF mzML

### ISSUE THREAD

**Issue by wenbostar** [compomics/moFF#32]
Hi,

I just tried the latest version of moFF. I got the following error using the example dataset.

```bash
~/anaconda2/bin/python moff_all.py --mbr off --tsv_list sample_data/20080311_CPTAC6_07_6A005.txt --raw_list sample_data/20080311_CPTAC6_07_6A005.mzML --tol 10 --loc_out output_moff
```
```
Starting Apex for sample_data/20080311_CPTAC6_07_6A005.txt ...
moff Input file: sample_data/20080311_CPTAC6_07_6A005.txt  XIC_tol 10.0 XIC_win 3.0000 moff_rtWin_peak 1.0000
RAW file  :  ['sample_data/20080311_CPTAC6_07_6A005.mzML']
Output file in :  output_moff
starting  peptide quantification (ms2 / matched ) ..
Traceback (most recent call last):
  File "/home/test/moFF/moff.py", line 612, in apex_multithr
    xic_data= get_xic_data (  flag_mzml, flag_windows, temp, loc_output, name_file, txic_path, loc,  0   )
  File "/home/test/moFF/moff.py", line 734, in get_xic_data
    run_temp = pymzml.run.Reader(raw_name)
NameError: global name 'raw_name' is not defined
```
Bo

**Comment by Maux82** [comment]
Hi, 

the new version it has not tested on mzML file. I let know when it will be fixed.
thanks for using moFF.
Andrea

**Comment by wenbostar** [comment]
Hi @Maux82, did you get a chance to take a look at this issue? Thanks a lot.
Bo

**Comment by antortjim** [comment]
Hi @wenbostar could you please share your txt file? I can look at the issue.

Thanks beforehand!

Antonio

**Comment by antortjim** [comment]
Forgot it's on sample_data of course :angel: Thanks anyway
Antonio
